# Generated by Django 2.2.6 on 2019-10-03 22:04

import PhotoDrive.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('album_id', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=250)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('directory', models.FileField(blank=True, null=True, upload_to=PhotoDrive.models.upload_to)),
                ('cover', models.ImageField(blank=True, null=True, upload_to=PhotoDrive.models.upload_to)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('first', models.CharField(max_length=250)),
                ('last', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250)),
                ('gender', models.CharField(max_length=250)),
                ('password', models.CharField(max_length=250)),
                ('profilepic', models.ImageField(blank=True, null=True, upload_to=PhotoDrive.models.upload_to)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('photo_id', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=250)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('url', models.ImageField(blank=True, null=True, upload_to=PhotoDrive.models.upload_to)),
                ('album_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='photo_album', to='PhotoDrive.Album')),
                ('liked', models.ManyToManyField(blank=True, related_name='photo', to='PhotoDrive.User')),
                ('visibleTo', models.ManyToManyField(blank=True, related_name='photo_visible', to='PhotoDrive.User')),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='liked',
            field=models.ManyToManyField(blank=True, related_name='album', to='PhotoDrive.User'),
        ),
        migrations.AddField(
            model_name='album',
            name='username',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='album_owner', to='PhotoDrive.User'),
        ),
        migrations.AddField(
            model_name='album',
            name='visibleTo',
            field=models.ManyToManyField(blank=True, related_name='album_visible', to='PhotoDrive.User'),
        ),
    ]
