# Generated by Django 2.2.6 on 2019-10-04 12:33

import PhotoDrive.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PhotoDrive', '0003_auto_20191003_2344'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='visible',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='photo',
            name='visible',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='album',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to=PhotoDrive.models.upload_to),
        ),
        migrations.AlterField(
            model_name='user',
            name='profilepic',
            field=models.ImageField(blank=True, null=True, upload_to=PhotoDrive.models.upload_to),
        ),
    ]
