# Generated by Django 2.2.6 on 2019-10-04 12:33

import PhotoDrive.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PhotoDrive', '0004_auto_20191004_1233'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='url',
            new_name='photo',
        ),
        migrations.AlterField(
            model_name='album',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to=PhotoDrive.models.upload_to),
        ),
        migrations.AlterField(
            model_name='user',
            name='profilepic',
            field=models.ImageField(blank=True, null=True, upload_to=PhotoDrive.models.upload_to),
        ),
    ]
